language: node_js

os: linux

node_js:
  - '12.14.1'

services:
  - postgresql

addons:
  apt:
    packages:
      - openjdk-8-jdk

env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
  - secure: OpPbpS47Vk9EEiHSQvNcBsMZZgkYDP2n1/KR7SGkbykJpMi5t2O9q08PT7TiOtKaADBuVIypZtiTrkoJPtKEgSVLWburLKGkheqt53yfa4iRt/A+J2Xw5gfK5Zi/loChton+fHr+xEQmDLswK8cz3GrbsOKVtx3v+2+C5UNkSSz3Pcdh5YVGCripZJV1mbUcq4w4+z1893+hFFnA4hnPG5rNmTSYvAJhsATWIhckF6VjZjjKKrVjm3iz3NokDnlk97Zig/pH0HF9XV/zv2UFTl344C3TV3+IlOLk2a0XalMtR03RAXHDYeIW93qWVag/+KiWVjqf5xgLI1VdmexJTcXBT04KrYJhUU5gvA2HbtuVwf9pLQr8wZmY+XTD7l7DgGl+Bl6syOwipxyMCmL3EB+E1eAB47qwcwLJ0j5F3LJZ8GMqrEbrnrJFdiLNHBDLhelKKHTg/VAzO3xl08OvkNGfbo3r8Vu0+GBbeBbjQTyzD2NOkukqxSMb2aohiSzctjrs79KPD22YCfCIhJaK1F/+y7eCwj2X/4ysVcoAqfh3xPlWDCZvekevtYh8s6iaeKQbFIA8jf6yl6YGeHAkRHBo1XzYikt9RAZQ5E7qo+knWfdswTnJd3zJax+rcx0b9Cs4xlnxULqMjaOgYwFaPyGP6Y93V5Gfts7oG6tjQgg=
  - secure: P/bGLC/iRf/yrxWLnwL9vMZysmesGA5vjkm25ocu+erjpMTA1qWO6MCfQ/0U7i8tpkB1BwGQmQCmR5IHqWuwX0iwPs6dgb27kNK7r8JlUc7QopZCY7L5Atq8Cfb18wwmu6g+dFVyRb0dpYZzvNMD3aDqUY48dikVqoCTlTKG1fC/FYtBdrzcNc34lc3RSjbEaB0VDJUw0theajnCwMO3KVKJ6bEss3jJ5hmcI3frojXo/8o8MW7tX+9UImnlLoZw/YagLZMABvd1Lvpqf+5+lHFNagL+Zv2Mo6Ip0bU2GWdEz76Jq70mJ84V0gzjKy42nFVNThXP9BpI3Gq9ZL6UuhFGxjSQRIHgOZjBQOZCwDwQqygl7fda+Ivln32si8WgAm1zRWE+BzYDF4ZXqVGVz7j3csUuPBROJLv72kzt0PjloORIjvOOWl2vGH24xtSM33f1XDbL31R+61Wv2G2lqnW8RGS2Z5UZycEGHNC/tB8ec4JQ/A+vBmhQd5yOhgGSDlpeFSjSKykiyps2Z2O0raQgmloUFFNq53p5pTPGP7ypD/Mz+EVOE8VUojfWX7F7WMBKVTraaWQVHGeAiWkFVOqM0ghtNAtNdNSzDW5EMctYvLWGAAw+hc6w8n0YuAqsc62V0x/G1HyGbbzVwJdEEsUA3LZUsmMvZ2Km6OnHUCk=
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script: |
  npm run lerna bootstrap
  npm run lerna run prepublishOnly

jobs:
  allow_failures:
    env:
      - ALLOWED_TO_FAIL=true
  include:
#    - name: "Dependency vulnerability check"
#      script:
#        - npm run snyk:test
#
#    - name: "Send snapshot to Snyk"
#      if: branch = master
#      env: ALLOWED_TO_FAIL=true
#      script:
#        - npm run snyk:monitor

#    - name: "Push client builds"
#      if: branch = master
#      script:
#        - npm run bootstrap-react-app
#        - npm run bootstrap-react-native-app
#        - travis/push-client-builds.sh

    - name: "Tests on generated app"
      # setup cuba postgres user; build and run backend app
      before_install: node scripts/ci-bootstrap-backend.js
      script:
        - npm run bootstrap-react-app
        - npm run validate-react-app
        - npm run build --prefix react-client-scr
        - npm run start-react-app &
        - sleep 120
        - npm test react-client-scr/ --prefix test-pup

    - name: "Unit tests, coverage and lint commits"
      # setup cuba postgres user; build and run backend app
      before_install: node scripts/ci-bootstrap-backend.js
      script:
        - commitlint-travis
        - npm run lerna run coverage

    - name: "front-generator - e2e - e2e:react:new-project"
      script:
        - npm run pack-react-client-libs
        - npm run test:e2e:react:new-project --prefix packages/jmix-front-generator

    - name: "front-generator - e2e - e2e:react:empty-model"
      script:
        - npm run pack-react-client-libs
        - npm run test:e2e:react:empty-model --prefix packages/jmix-front-generator

    - name: "front-generator - e2e - e2e:sdk"
      script:
        - npm run pack-react-client-libs
        - npm run test:e2e:sdk --prefix packages/jmix-front-generator

#    - name: "front-generator - e2e - e2e:react:scr os: windows"
#      os:
#        - windows
#      script: npx mocha 'test\e2e\react-client--scr.test.js' -g 'test:e2e:react:scr' --timeout 0
