language: node_js

os: linux

node_js:
  - '12.14.1'

services:
  - postgresql

addons:
  apt:
    packages:
      - openjdk-8-jdk

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script: |
  npm run lerna bootstrap
  npm run lerna run prepublishOnly

jobs:
  include:
    - name: "Tests on generated app"
      # setup cuba postgres user; build and run backend app
      before_install: node scripts/ci-bootstrap-backend.js
      script:
        - npm run bootstrap-react-app
        - npm run validate-react-app
        - npm run start-react-app &
        - sleep 60
        - npm test react-client-scr/ --prefix test-pup

    - name: "Tests on generated app - backward compatibility 7.1"
      # setup cuba postgres user; build and run backend app
      before_install: node scripts/ci-bootstrap-backend.js sample-car-rent-7-1
      script:
        - npm run bootstrap-react-app
        - npm run validate-react-app
        - npm run start-react-app &
        - sleep 60
        - npm test react-client-scr/app-start.test.js --prefix test-pup
        - npm test react-client-scr-71 --prefix test-pup

    - name: "Unit tests, coverage and lint commits"
      # setup cuba postgres user; build and run backend app
      before_install: node scripts/ci-bootstrap-backend.js
      script:
        - commitlint-travis
        - npm run lerna run coverage

    - name: "front-generator - e2e - e2e:react:new-project"
      script: npm run test:e2e:react:new-project --prefix packages/front-generator

    - name: "front-generator - e2e - e2e:react:empty-model"
      script: npm run test:e2e:react:empty-model --prefix packages/front-generator

    - name: "front-generator - e2e - e2e:sdk"
      script: npm run test:e2e:sdk --prefix packages/front-generator

    - name: "front-generator - e2e - e2e:polymer2"
      script: npm run test:e2e:polymer2 --prefix packages/front-generator

    - name: "front-generator - e2e - e2e:polymer2-ts"
      script: npm run test:e2e:polymer2-ts --prefix packages/front-generator

#    - name: "front-generator - e2e - e2e:react:scr os: windows"
#      os:
#        - windows
#      script: npx mocha 'test\e2e\react-client--scr.test.js' -g 'test:e2e:react:scr' --timeout 0

